quarto:
  plugins:
    - quarto-fontawesome
  
project:
  type: website

website:
  title: "KAI"
  page-navigation: true
  site-url: "https://isss608-kaixin.netlify.app//"

  favicon: images/favicon.png
  
  navbar:
    title: false
    logo: "images/name_logo.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "**1**: A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "**2**: Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "**3**.1: Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html"
          - text: "3.2: Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
          - text: "**4**.1: Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html"
          - text: "4.2: Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html"
          - text: "4.3: Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html"
          - text: "4.4: Building Funnel Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.html"
          - text: "**5**.1: Building Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_1.html"
          - text: "5.2: Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_2.html"
          - text: "5.3: Visual Multivariate Analysis with Heatmap"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_3.html"
          - text: "5.4: Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_4.html"
          - text: "5.5: Treemap Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_5.html"
          - text: "**6**: Visualising and Analysing Time-oriented Data"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "**7**.1: Choropleth Mapping in R"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_1.html"
          - text: "7.2: Visualising Geospatial Point Data"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_2.html"
          - text: "7.3: Analytical Mapping"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_3.html"
          - text: "**8**: Modelling, Visualising and Analysing Network Data with R"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "**9**: Visualising and Analysing Text Data"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          - text: "**10**: Information Dashboard Design: R methods"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
            
      - text: "In-class Exercise"
        menu:
          - text: "1: Now You See It!"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "2: Designing Graphs to Enlighten"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "3: Interactivity in Visual Analytics"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "4: Fundamentals of Visual Analytics"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "5: Shiny Basics"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "6: Visualising and Analysing Time-Oriented Data"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "7: Visualising and Analysing Geographic Data"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "8: Network Data Visualisation and Analysis"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
      - text: "Take-home Exercise"
        menu:
          - text: "1: Creating data visualisation beyond default"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "2: Peer critique and DataVis Makeover"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "3: Be Weatherwise or Otherwise"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
          - text: "4: Prototyping Modules for Visual Analytics Shiny Application"
            href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
    right: 
      - href: index.qmd
        text: Home

  page-footer:
    left: "Blog made using [Quarto®](https://quarto.org/)"
    right:
#      - icon: github
#        href: https://github.com/kaixx1027
      - icon: house
        href: mailto:happykai923@gmail.com

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: On this page
    html-math-method: katex
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-link: true
    df-print: paged

editor: visual

