quarto:
  plugins:
    - quarto-fontawesome
  
project:
  type: website

website:
  title: "KAI"
  page-navigation: true
  site-url: "https://isss608-kaixin.netlify.app//"

  favicon: images/favicon.png
  
  navbar:
    title: false
    logo: "images/name_logo.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "1: A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "2: Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "3.1: Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html"
          - text: "3.2: Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
      - text: "In-class Exercise"
        menu:
          - text: "1: Now You See It!"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "2: Designing Graphs to Enlighten"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
      - text: "Take-home Exercise"
        menu:
          - text: "1: Creating data visualisation beyond default"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right: 
      - href: index.qmd
        text: Home

  page-footer:
    left: "Blog made using [Quarto®](https://quarto.org/)"
    right:
#      - icon: github
#        href: https://github.com/kaixx1027
      - icon: house
        href: mailto:happykai923@gmail.com

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: On this page
    html-math-method: katex
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-link: true
    df-print: paged

editor: visual

